### ISSUE TITLE
Bugs documentation from playground kotlin dsl

### ISSUE THREAD

**Issue by hernandazevedozup** [ZupIT/docs-beagle#322]
Ao testar o playground com a nova feature de Beagle DSL, eu usei os próprios exemplos da documentação (aba Kotlin). Acabei encontrando alguns problemas. Vou listá-los aqui:

Accessibility
"iner": o início da palavra foi cortada. Corrigir para "Container"

------------
 
Button
falta uma vírgula após "Click me!" 

------------

Imagem local
não funcionou. Tive que substituir por:
    
```kotlin
      Image(
    ImagePath.Local.both(
        "public/web-illustration.png",
        "mobileIllustration"
    )
)
```

Imagem remota
não funcionou. Tive que substituir por
    
    ```kotlin

      Image(
    ImagePath.Remote("https://mcdn.wallpapersafari.com/medium/8/37/zlwnoM.jpg")
)

```
------------

 

WebView
substituir "url:" por "url ="

------------

LazyComponent
Eu já tinha comentado isso, é um problema no exemplo JSON e no Kotlin. O path do lazy component é o endereço da própria view do LazyComponent. Isso cria um loop infinito. Substituir "path" por algum outro arquivo como: "button.json".

 
------------

 
ListView
Para que funcione no Playground, não podemos usar classes/enum que não existem. A classe até que conseguimos declarar (o código no playground roda dentro de uma função no Kotlin). Mas o enum não é possível, pois enums não podem ser declarados dentro de funções.

 
Um ponto de atenção é que o dataSource de um listView, no backend, aceita apenas expressões. Isso é intencional? Pelo menos no web, aceitamos também listas.
 

A seguir, um exemplo que funciona no playground:
    
        
    ```kotlin
  {
    data class Person (
            val name: String,
            val race: String,
            val planet: String,
            val isMistborn: Boolean,
            val age: Int,
            val sex: String
    )
    
    val characters = listOf(
        Person(
            name = "Kelsier",
            race = "Half-skaa",
            planet = "Scadrial",
            isMistborn = true,
            age = 38,
            sex = "male"
        ),
        Person(
            name = "Vin",
            race = "Half-skaa",
            planet = "Scadrial",
            isMistborn = true,
            age = 20,
            sex = "female"
        ),
        Person(
            name = "TenSoon",
            race = "Kandra",
            planet = "Scadrial",
            isMistborn = false,
            age = 40,
            sex = "male"
        ),
    )
    
    ListView(
        context = ContextData(id = "characters", value = characters),
        dataSource = expressionOf("@{characters}"),
        template = Container(
            children = listOf(
                Text("Name: @{item.name}"),
                Text("Race: @{item.race}"),
                Text("Mistborn: @{item.isMistborn}"),
                Text("Planet: @{item.planet}"),
                Text("sex: @{item.sex}"),
                Text("age: @{item.age}"),
            )
        ).applyStyle(
            Style(
                margin = EdgeValue(bottom = 20.unitReal())
            )
        )
    )
}()
    
```

------------

 

PageView
não use constantes que não estão na lib do Beagle (BLACK, por exemplo). Substituir constantes de cor por valores hexadecimais.

 
------------

SimpleForm
Cuidado com o excesso de parentêses. Essa sintaxe é inválida no Kotlin. Corrigi para o seguinte:
   
      
       
    
      ```kotlin
SimpleForm(
  context = ContextData(id = "myContext", value = ""),
  children = listOf(
    TextInput(
      value = "@{myContext}",
      placeholder = "Type in your password",
      onChange = listOf(
        SetContext(contextId = "myContext", value = "@{onChange.value}")
      )
    ),
    Button(text = "Click to Submit", onPress = listOf(SubmitForm()))
  ),
  onSubmit = listOf(
    Alert(
      title = "Data submited",
      message = "The password is " + "@{myContext}"
    )
  )
)  
```
  
Aqui pode ser encontrado um projeto no Playground com todas essas correções: 
http://playground-beta.usebeagle.io/#/cloud/9ba95e9b1d4f406aa63482c5b2fd15ae/accessibility.kt

**Comment by carlossteinzup** [comment]
- [ ] acessibility

**Comment by carlossteinzup** [comment]
Corrigi todos os exemplos na DOCs e adicionei as sugestões.
