### ISSUE TITLE
The image in step three not showing

### ISSUE THREAD

**Issue by uziasferreirazup** [ZupIT/docs-beagle#422]
## Description
Step three not showing the image: https://docs.usebeagle.io/v1.6/get-started/using-beagle/android/

## Expected Results
Show the image.

##  Example, screenshot:
<img width="940" alt="Screen Shot 2021-03-18 at 20 14 18" src="https://user-images.githubusercontent.com/63263091/111709542-89627d00-8826-11eb-9c68-362f5fa583f9.png">

**Comment by carlossteinzup** [comment]
#429 
#430 
#431

**Comment by carlossteinzup** [comment]
@uziasferreirazup I have corrected this issue. At this time it was necessary to correct it in a few branchs since it is an issue that affected the older versions and the latest one.

**Comment by carlossteinzup** [comment]
Done. PRs confirmed and merged
