### ISSUE TITLE
[UPDATE DOC] Deprecated State

### ISSUE THREAD

**Issue by hernandazevedozup** [ZupIT/docs-beagle#465]
Estava olhando a docs do beagle para "custom beagle activity" na versão 1.6.0 para android
https://docs.usebeagle.io/v1.6/resources/customization/beagle-for-android/custom-beagle-activity/

Na sessão 4 tem uma referência ao ServerDrivenState.Loading, que está com a annotation @deprecated na lib dessa versão.  Seria legal se tivesse um warning dizendo que esta descontinuado e um exemplo de como fazer atualmente usando ServerDrivenState.Started e ServerDrivenState.Finished

**Comment by carlossteinzup** [comment]
Não seria interessante já colocar os exemplos de Started e Finished no locar do loading já que na 1.6 esse é o modelo? E remover o loading.

**Comment by carlossteinzup** [comment]
https://github.com/ZupIT/docs-beagle/pull/474
https://github.com/ZupIT/docs-beagle/pull/473

**Comment by carlossteinzup** [comment]
done
