### ISSUE TITLE
Problemas de tradução no menu lateral direito (Edit this page, create child page...) e no feedback da pagina (localizado no rodapé)

### ISSUE THREAD

**Issue by luismaximozup** [ZupIT/docs-beagle#48]
Ambos estão em ingles, e o ideal seria deixa-los de acordo com o idioma escolhido, assim como é na doc do kubernets

https://kubernetes.io/pt/docs/setup/

**Comment by carlossteinzup** [comment]
Atualizado. As opções de edição agora estão de acordo com o idioma da página
